/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ieexp3_library_VE026A_JNI */

#ifndef _Included_ieexp3_library_VE026A_JNI
#define _Included_ieexp3_library_VE026A_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    Cao_InitDCOM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_Cao_1InitDCOM
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    Cao_UninitDCOM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ieexp3_library_VE026A_1JNI_Cao_1UninitDCOM
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    Cao_CreateEngine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_Cao_1CreateEngine
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    Cao_ClearEngine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_Cao_1ClearEngine
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoEngine_Workspaces
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoEngine_1Workspaces
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoEngine_AddWorkspace
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoEngine_1AddWorkspace
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoWorkspaces_Count
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ieexp3_library_VE026A_1JNI_CaoWorkspaces_1Count
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoWorkspaces_Add
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoWorkspaces_1Add
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoWorkspaces_Clear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoWorkspaces_1Clear
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoWorkspaces_Item
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoWorkspaces_1Item
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoWorkspaces_Remove
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoWorkspaces_1Remove
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoWorkspace_Controllers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoWorkspace_1Controllers
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoWorkspace_Index
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ieexp3_library_VE026A_1JNI_CaoWorkspace_1Index
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoWorkspace_Name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ieexp3_library_VE026A_1JNI_CaoWorkspace_1Name
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoWorkspace_AddController
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoWorkspace_1AddController
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoControllers_Count
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ieexp3_library_VE026A_1JNI_CaoControllers_1Count
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoControllers_Add
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoControllers_1Add
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoControllers_Clear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoControllers_1Clear
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoControllers_Item
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoControllers_1Item
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoControllers_Remove
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoControllers_1Remove
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoController_Index
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ieexp3_library_VE026A_1JNI_CaoController_1Index
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoController_Name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ieexp3_library_VE026A_1JNI_CaoController_1Name
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoController_Robots
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoController_1Robots
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoController_Tasks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoController_1Tasks
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoController_Variables
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoController_1Variables
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoController_AddRobot
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoController_1AddRobot
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoController_AddTask
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoController_1AddTask
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoController_AddVariable
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoController_1AddVariable
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoController_Execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ieexp3_library_VE026A_1JNI_CaoController_1Execute
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobots_Count
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobots_1Count
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobots_Add
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobots_1Add
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobots_Clear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobots_1Clear
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobots_Item
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobots_1Item
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobots_Remove
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobots_1Remove
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Index
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Index
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Name
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Variables
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Variables
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Accelerate
 * Signature: (JFF)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Accelerate
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_AddVariable
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1AddVariable
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Change
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Change
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Execute_Motor
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Execute_1Motor
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Execute_ExtSpeed
 * Signature: (FFF)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Execute_1ExtSpeed
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Execute_TakeArm
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Execute_1TakeArm
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Execute_GiveArm
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Execute_1GiveArm
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Execute_Draw
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Execute_1Draw
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Execute_Approach
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Execute_1Approach
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Execute_Depart
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Execute_1Depart
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Execute_DriveEx
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Execute_1DriveEx
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Execute_DriveAEx
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Execute_1DriveAEx
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Execute_RotateH
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Execute_1RotateH
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Hold
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Hold
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Halt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Halt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Move
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Move
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Rotate
 * Signature: (Ljava/lang/String;FLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Rotate
  (JNIEnv *, jobject, jstring, jfloat, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Speed
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Speed
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoRobot_Unhold
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoRobot_1Unhold
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoTasks_Count
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ieexp3_library_VE026A_1JNI_CaoTasks_1Count
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoTasks_Add
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoTasks_1Add
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoTasks_Clear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoTasks_1Clear
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoTasks_Item
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoTasks_1Item
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoTasks_Remove
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoTasks_1Remove
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoTask_Index
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ieexp3_library_VE026A_1JNI_CaoTask_1Index
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoTask_Name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ieexp3_library_VE026A_1JNI_CaoTask_1Name
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoTask_Variables
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoTask_1Variables
  (JNIEnv *, jobject);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoTask_AddVariable
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoTask_1AddVariable
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoTask_Delete
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoTask_1Delete
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoTask_Execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ieexp3_library_VE026A_1JNI_CaoTask_1Execute
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoTask_Start
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoTask_1Start
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoTask_Stop
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoTask_1Stop
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoVariables_Count
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ieexp3_library_VE026A_1JNI_CaoVariables_1Count
  (JNIEnv *, jobject, jint);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoVariables_Add
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoVariables_1Add
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoVariables_Clear
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoVariables_1Clear
  (JNIEnv *, jobject, jint);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoVariables_Item
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoVariables_1Item
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoVariables_Remove
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoVariables_1Remove
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoVariable_Index
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ieexp3_library_VE026A_1JNI_CaoVariable_1Index
  (JNIEnv *, jobject, jint);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoVariable_Name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ieexp3_library_VE026A_1JNI_CaoVariable_1Name
  (JNIEnv *, jobject, jint);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoVariable_GetValue
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ieexp3_library_VE026A_1JNI_CaoVariable_1GetValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     ieexp3_library_VE026A_JNI
 * Method:    CaoVariable_PutValue
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ieexp3_library_VE026A_1JNI_CaoVariable_1PutValue
  (JNIEnv *, jobject, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
